
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PROGRAM = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int POINT = 3;
  public static final int SEMICOLUN = 5;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int END = 7;
  public static final int BEGIN = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "POINT",
  "COMMA",
  "SEMICOLUN",
  "BEGIN",
  "END",
  "PROGRAM"
  };
}

