
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IDENTIFIER = 49;
  public static final int CHARACTER_STRING = 50;
  public static final int REAL = 73;
  public static final int GT = 58;
  public static final int PACKED = 31;
  public static final int TYPE = 41;
  public static final int STARSTAR = 69;
  public static final int CONST = 5;
  public static final int GE = 57;
  public static final int UNTIL = 43;
  public static final int ASSIGNMENT = 51;
  public static final int COMMA = 53;
  public static final int RPAREN = 68;
  public static final int LT = 62;
  public static final int INTEGER = 71;
  public static final int LPAREN = 61;
  public static final int FALSE = 76;
  public static final int NOT = 7;
  public static final int LE = 60;
  public static final int NIL = 29;
  public static final int ARRAY = 2;
  public static final int VAR = 45;
  public static final int THEN = 39;
  public static final int GOTO = 23;
  public static final int PBEGIN = 64;
  public static final int UPARROW = 70;
  public static final int EXTERNAL = 37;
  public static final int RECORD = 34;
  public static final int MOD = 13;
  public static final int SLASH = 14;
  public static final int TRUE = 75;
  public static final int PLUS = 11;
  public static final int UNIT = 42;
  public static final int WHILE = 46;
  public static final int EQUAL = 56;
  public static final int IMPLEMENTATION = 25;
  public static final int CHAR = 74;
  public static final int INTERFACE = 27;
  public static final int BOOLEAN = 72;
  public static final int DO = 15;
  public static final int DIGSEQ = 54;
  public static final int FOR = 20;
  public static final int STAR = 10;
  public static final int DIV = 12;
  public static final int DOWNTO = 16;
  public static final int ELSE = 17;
  public static final int DOTDOT = 55;
  public static final int DOT = 78;
  public static final int PROCEDURE = 32;
  public static final int SEMICOLON = 77;
  public static final int EOF = 0;
  public static final int FUNCTION = 22;
  public static final int REPEAT = 35;
  public static final int LABEL = 28;
  public static final int MINUS = 9;
  public static final int IN = 26;
  public static final int OR = 8;
  public static final int SET = 36;
  public static final int error = 1;
  public static final int PFILE = 65;
  public static final int IF = 24;
  public static final int RBRAC = 66;
  public static final int OF = 30;
  public static final int END = 18;
  public static final int COLON = 52;
  public static final int FILE = 19;
  public static final int NOTEQUAL = 63;
  public static final int BEGIN = 3;
  public static final int CASE = 4;
  public static final int FORWARD = 21;
  public static final int STRING = 38;
  public static final int LBRAC = 59;
  public static final int PROGRAM = 33;
  public static final int AND = 6;
  public static final int TO = 40;
  public static final int REALNUMBER = 67;
  public static final int WITH = 47;
  public static final int USES = 44;
  public static final int XOR = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARRAY",
  "BEGIN",
  "CASE",
  "CONST",
  "AND",
  "NOT",
  "OR",
  "MINUS",
  "STAR",
  "PLUS",
  "DIV",
  "MOD",
  "SLASH",
  "DO",
  "DOWNTO",
  "ELSE",
  "END",
  "FILE",
  "FOR",
  "FORWARD",
  "FUNCTION",
  "GOTO",
  "IF",
  "IMPLEMENTATION",
  "IN",
  "INTERFACE",
  "LABEL",
  "NIL",
  "OF",
  "PACKED",
  "PROCEDURE",
  "PROGRAM",
  "RECORD",
  "REPEAT",
  "SET",
  "EXTERNAL",
  "STRING",
  "THEN",
  "TO",
  "TYPE",
  "UNIT",
  "UNTIL",
  "USES",
  "VAR",
  "WHILE",
  "WITH",
  "XOR",
  "IDENTIFIER",
  "CHARACTER_STRING",
  "ASSIGNMENT",
  "COLON",
  "COMMA",
  "DIGSEQ",
  "DOTDOT",
  "EQUAL",
  "GE",
  "GT",
  "LBRAC",
  "LE",
  "LPAREN",
  "LT",
  "NOTEQUAL",
  "PBEGIN",
  "PFILE",
  "RBRAC",
  "REALNUMBER",
  "RPAREN",
  "STARSTAR",
  "UPARROW",
  "INTEGER",
  "BOOLEAN",
  "REAL",
  "CHAR",
  "TRUE",
  "FALSE",
  "SEMICOLON",
  "DOT"
  };
}

